language: python
python:
- 2.7
sudo: required
env:
  global:
  - GH_USERNAME=pierre-rouanet
  - GH_REPO=poppy-docs
  - GIT_EMAIL=poppy-bot-ci@inria.fr
  - GIT_NAME=poppy-bot
  - secure: LkAbWxBOLpxNwe59YQx3oRfv1OUmbSSJ6LpOTen8CpOykHOCqKTwDj3pTAhmoY9gKD3r3f+GrP2Jdrtb0a4B96YyJPQ81xF2ElVnRGc4syxW1hWiWJ0hpzA2i2OobDDup5IOzYfNDOJtghSJj/R2qR7WP3w8MyDrKsYQJ59gngtU10/DE7Vp1ABjZCjblQPz1rHxXmq7KvQY7eF2rII4en6HL71QEybRlEEUBbxudQnkJ3HgofVrScsH/irvpuJkvFrwvh6NOj8ygg9E52oozZOL9USQrhWYTyHxOcrD868bt9LGEV3Flg5Us+kGyKJfXiMH48yu4OeQgsK5pQoIOH7lQFShlVIUzV1UxFgthugVU0tdtEbeoZjcagT+DWaGtudZmgRy7BjS14+Ss/8oXNl1lu75JT1AjuIwxn/HFHK0YsGf1ppdMc2XuRTRkRNGK5vP+v+79m/WeJzhTcz0rZ7GdljIDB6LbjcNP0NbUb1/4MmBB9Rz4MOtrBPpthFO0xF4Gxvt/u6xRX/AszOFtb5NoXzPsLkXka0nVeGmxw2XZCZ/3dy0klGRQdt/+e2YYT9b1ZN1RxjeYP8cn027nFMdFAYo0HYt44qzw7hyZqix0eY5caGbimSm3BX+e1MIKlQYhczH4GbC4sWQuYrqooOxU6uPb3McGHp33QNOpgM=
  - secure: fiV6wdl3PlqYnGrsGC5eIbqhWJmRuY4AE8KE6sqTt99cVehXAQQ/45CNcYD38W2mLrhNzAiQ6pO77GTUDlU5jz8X9fgLmg1TiA1tGdvJslRgZe8O1GtNQ41O743NpWhMehTL9NMYvVuwcBlFrKQxzI64DVkxRWnS9+d7qAq2VO/aDSq+77YKyKAUleJZ0Ax359kI2tLmBPNiT2InZ/i+s/i4zSsoz9SFneTo4F4HuBN78jjjKMt7/cDWbTLsk4BLdhEVTDJOT/DKW+ceC4bTNvo3F0dRxxtOSzd48LDTzCW/LMuprirkj6WUJhH0fLyon3bBrsD2bWaMbhyp6MZS5hhRkTR+AJSkE/B1K8U0nClPydfE9vqbcg+GObEkfLQTEEBr/wfIGeF7DwG4gCOgDbh5Ua98cYxhWL2Ekui0j39nT9vlN5TdhvE5/A4aQVQHG7svAOymskEWWPFcSsAtX0Ywn/vDEUw7sCqS0HBOcayLdcOoq4sWEPo+Gc1b7MWyw/5Vwh23ZzXw/NDP3SYWSaFfERINVkFhJLVA28SauD7tyKw6eV8tI2oYnZgrVUQ32lxThoYAMKlEND+J+DIX5ZS6QsRR80JeSL9P6wjSE0vAYozvMLofoaa4Jpbr2qOR4YoS/jQQd14QWrx9+k7OoHDtzBUEg6Ia6rH5YvHTLDU=
addons:
  apt:
    packages:
    - texlive
    - texlive-latex-extra
    - dvipng
    - lmodern
before_install:
- ". ./ci/before_install.sh"
script:
- ". ./ci/update_documentation.sh"
notifications:
  email:
  - poppy-bot-ci@inria.fr
  on_failure: change
  on_success: change
