language: python
python:
- 2.7
sudo: required
env:
  global:
  - GH_USERNAME: poppy-project
  - GH_REPO: poppy-docs
  - GIT_EMAIL: poppy-bot-ci@inria.fr
  - GIT_NAME: poppy-bot
  - secure: "u0offpVnqv44Xl+s5CKHidB7rYnOheS80kGJvGLdp/zTgr3BjFNizAzZSA+D1zVpjSOteKfICwkK74wPQUp+sSCUa1Y73Fo2mS6J81ON3N9r0xdQ4FABQjSkZfC0kXQAGIScQre+7h2j5RjdqGvmUIfTWdYE+ttEXnyolhzrInuNAUpmxEpKVSxONmcMaPoFhArRdNZDyCPIpsh2idLimKRGUo3Ghw5ZC7nzktmt4lH1+WeCLb2mv8NgiJRwH9/TJINMM7c5MM4NDfFSiv+EUWuEosVoTpKBTOBh9zcV6v+g1iIFkwADKW17dpm1J6X9RrGH00kflGq6g0zeDUibMWEjEEHai29l0Yj8lh+nkNSwTpvBsQRv68LTPexcZHqBvO76d6RcLo+M7psKhYJ9wvpImCsveKK1de+OHrUuS3r/oQ2T7U8ljjjgJvPGinxkKowCMG/DtOSPqfgNoJBWRjFXpmMqCCcePC2GFh1UV3w7CMhls5CKB2vfuvKmFdvru8SLZOe2wcJ/UKfF6lZQ7YarQ91eGTtWWFkOmAnr65/Mo3By+3KeAu3LQDuGFq/e4oPzUVYDhKnoJ8zwERleqXjT27qLVwFRmn33waR2Bl9mkLYMrf7ZSEzOYs4QaW4REZch+gRgAOcNOEs6M25XVtrjLxwyh89gNJGFzeftJ2g="

addons:
  apt:
    packages:
    - texlive
    - texlive-latex-extra
    - dvipng
    - lmodern
before_install:
- ". ./ci/before_install.sh"
script:
- ". ./ci/update_documentation.sh"
notifications:
  email:
  - poppy-bot-ci@inria.fr
  on_failure: change
  on_success: change
