files:
  - source: /en/**/*.md
    ignore:
      - '*.png'
      - '*.jpg'
      - '*.ttf'
      - '*.svg'
      - '*.eot'
      - '*.woff*'
      - '*.gif'
      - '*.PNG'
      - '*.pdf'
    translation: /%two_letters_code%/**/%original_file_name%
